global:
  envs:
    USER_BASE_DN: dc=sampleCiam.com
    ENVIRONMENT_NAME: unisys
    DOMAIN_NAME: ping-devops.com
  labels:
    facile.pingidentity.cloud/admin-env-id: d159739d-9eeb-4c83-8208-551acfdda03e
    facile.pingidentity.cloud/admin-user-id: dd476d20-fbb0-44e8-b037-064ef51f1435
pingOne:
  envRegion: NA
  administration:
    useMyPing: true
    envId: d159739d-9eeb-4c83-8208-551acfdda03e
    adminUserId: dd476d20-fbb0-44e8-b037-064ef51f1435
    workerApp:
      id: 817ad030-8051-46e8-ab7a-e311fb46fca4
      secret: gY2YJH7cG.9Uug269pEQHeBlOgLUqVf4x_DRjh4B6gV933l6G3_w3hO7QZZ~GRqI
    pfLogonApp:
      id: 5655701a-8a21-4083-99a4-a9aea7b95b36
      secret: P5R9JAHmL1T7K521G42UF_wzn4t52gSxMGN0u2-C1TCECD_-yJQL8-Jm2mZ8alp8
    paLogonApp:
      id: 85e19832-6d9c-4e33-b0f6-a865a61fa611
      secret: KCa8H6cGwb6sBjrhxje3wR.REuQUNB6EGJG3UxgFcptTv7zV7z3Upnpt75h~IeU.
    pdLogonApp:
      id: 85e19832-6d9c-4e33-b0f6-a865a61fa611
      secret: KCa8H6cGwb6sBjrhxje3wR.REuQUNB6EGJG3UxgFcptTv7zV7z3Upnpt75h~IeU.
usePingConfig:
  enabled: true
baseline:
  directory:
    enabled: true
capabilities:
  authenticationAuthority:
    enabled: true
  multiFactorAuthentication:
    enabled: true
  accessManager:
    enabled: true
  dynamicAuthorization:
    enabled: false
  risk:
    enabled: true
  verify:
    enabled: true
useCases:
  ciba:
    enabled: false
  consentManagement:
    enabled: true
  delegatedAdministration:
    enabled: true
  accessControl:
    enabled: true
  scim:
    enabled: false
  socialConnections:
    enabled: false
  userProfiles:
    enabled: true
  verifyDemoEnv:
    enabled: true
ping-devops:
  pingfederate-admin:
    enabled: true
    envs:
      SERVER_PROFILE_URL: https://github.com/hinespj/seipoc.git
      SERVER_PROFILE_PATH: server-profile/pingfederate
      SERVER_PROFILE_BRANCH: main
    workload:
      type: StatefulSet
  pingfederate-engine:
    enabled: true
    envs:
      SERVER_PROFILE_URL: https://github.com/hinespj/seipoc.git
      SERVER_PROFILE_PATH: server-profile/pingfederate
      SERVER_PROFILE_BRANCH: main
      TAIL_LOG_FILES: /opt/out/instance/log/audit.log /opt/out/instance/log/server.log
      PF_LOG_LEVEL: DEBUG
  pingdirectory:
    enabled: true
  pingdatasync:
    enabled: true
  pingaccess-admin:
    enabled: true
  pingaccess-engine:
    enabled: true
    envs:
      TAIL_LOG_FILES: >-
        /opt/out/instance/log/pingaccess_engine_audit.log
        /opt/out/instance/log/pingaccess.log
  pingdatagovernance:
    enabled: false
  pingdatagovernancepap:
    enabled: false
  pingdelegator:
    enabled: true
